<?php

/**
 * Remove the following html header elements by default:
 * - Windows Live Writer
 * - Theme version meta
 * - WordPress version meta
 */
$html_header_elements = array(
	'wlw', // Windows Live Writer meta
	'wp_version', // WordPress Core version
	'theme_version' // Theme version generated by Hybrid Core Library
);

/* Allow themes to prevent the removal of html header elements */
$html_header_elements = apply_filters( 'ejo_remove_html_header_elements', $html_header_elements );

/* Windows Live Writer manifest */
if (isset($html_header_elements['wlw'])) {

	remove_action( 'wp_head', 'wlwmanifest_link' ); 
}

/* WordPress version meta */
if (isset($html_header_elements['wp_version'])) {

	remove_action( 'wp_head', 'wp_generator' ); 
}
